apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: argo-success-rate
spec:
  # this analysis template requires a service name and namespace to be supplied to the query
  args:
  - name: service
  metrics:
  - name: success-rate
    initialDelay: 60s
    interval: 20s
    successCondition: result[0] >= 0.8
    failureCondition: result[0] < 0.8
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        query: >+
          sum(irate(istio_requests_total{destination_service="argo-rollout-canary.argo.svc.cluster.local",reporter="source",response_code=~"2.*"}[1m]
          ))/
          sum(irate(istio_requests_total{destination_service="argo-rollout-canary.argo.svc.cluster.local",reporter="source"}[1m]))
  